### ISSUE TITLE
[Feature Request] Sync OH Schedule with Given Google Calendar

### ISSUE THREAD

**Issue by developStorm** [CarsonHoffman/office-hours-queue#25]
Resolves issues like #19. This should be very handy when OH schedule needs ad-hoc changes and as well as for class that don't necessarily has same OH schedule from week to week.

There may still be some issues with the actual implementation, such as most courses mix listing virtual office hours with in-person office or [even lectures](https://eecs388.org/index.html). This can be solved by synchronizing only events with a specific pattern in name.

**Comment by CarsonHoffman** [comment]
I think that this is out of scope for the queue itself given the various complexities across different courses as you alluded to. You're free to pull that information on your end and hit the schedule API endpoint manually.

**Comment by y2kmurali** [comment]
Might it also be possible to have a "manual OH" mode instead of the scheduling to allow courses to have one source of truth (e.g. a google calendar or something) and then instructors can just manually open/close the queue when holding OH? That was our workflow on the old OH queue and it seemed to work fine. 

I have no issues with the scheduling system as a whole but I totally can see how inconsistencies can lead to issues if the OH queue doesn't align with other sources.
