### ISSUE TITLE
Differentiate between in-person and hybrid/virtual OH queues

### ISSUE THREAD

**Issue by zjweiss** [CarsonHoffman/office-hours-queue#27]
When an instructor clicks on "help" it says their "link is: <user inputted location>" (see highlighted area below).

<img width="390" alt="image" src="https://user-images.githubusercontent.com/70495470/155761536-01034e51-7a2f-46f0-9bbd-97e192993b8b.png">
 
This makes sense for online OH, however, for in-person it doesn't make perfect sense.

Additionally, when signing up for a queue it asks for a "location/meeting link" (see highlighted below)

<img width="287" alt="image" src="https://user-images.githubusercontent.com/70495470/155761745-8c069363-a877-49e9-8518-596d84926dfc.png">

It could be nice to just display to appropriate message (ie location for in-person and meeting link for virtual).

It could be nice to have a feature that allows instructors to designate whether a queue is in-person/online and display the appropriate messages.

I know this is a low-level request, but I thought it could be worth mentioning.

**Comment by CarsonHoffman** [comment]
I just added this in https://github.com/CarsonHoffman/office-hours-queue/commit/fefa77da652cdd71814242f6376c59fc4b39942d. Because it involves server changes I'll need to wait until tonight to deploy this, but here's a quick preview:
<img width="382" alt="image" src="https://user-images.githubusercontent.com/19721219/155801995-86577b31-a8dc-4394-ba27-0764f433b1ba.png">
<img width="421" alt="image" src="https://user-images.githubusercontent.com/19721219/155801893-74f01eaf-2ee4-4dcb-8da0-af8a9bd72902.png">
<img width="417" alt="image" src="https://user-images.githubusercontent.com/19721219/155801897-25b66906-cc7b-483a-b22f-63767c959e08.png">
