### ISSUE TITLE
[Enhancement] “Unordered Set” Stage in Between Queue to Stack

### ISSUE THREAD

**Issue by developStorm** [CarsonHoffman/office-hours-queue#40]
I think it would be good to have an intermediate status of "currently being helped" when an staff member clicks on the "Help" button, instead of the "Popped!" modal we have now. This:

1. Provides students with greater transparency about the state of the queue. When the OH goes slow, students may ask why they went to the front of the queue and still haven't received help - this intermediate stage can help clarify such issues.
2. Prevent staff mistakes from causing unwanted/confusing pop-ups on the student side - accidentally clicking on help or not helped (this often requires pinning the student to fix, which causes even more pop-ups on the student side). Alleviate issues such as https://github.com/CarsonHoffman/office-hours-queue/issues/8#issuecomment-767767625
3. Allows staff to interact with other elements on the queue page. For example - message to student. Solves issues like #15. 

Desired UI would look like this:

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/59678453/217168878-63c9142b-944b-4c4f-bdfe-bbf7fc6495cc.png">

**Comment by CarsonHoffman** [comment]
I really like this idea! In terms of UI, I think it might be simpler to just put an icon next to the entry, similar to pinning. (Having two separate sections might make for some weird transitions, and I think the icon would still get the point across.) What do you think on that?

**Comment by developStorm** [comment]
An icon should suffice! I think  it might appear to be less clear what that icon is for (on student side) and why the button "suddenly" changed (on instructor side) if we don't explicitly show the intermediate stage, but anyway it's not that hard to figure out - people should get familiar to it after a few initial rounds.

**Comment by CarsonHoffman** [comment]
Yeah, I'd definitely put a tooltip on it explaining the state when you hover over the icon and it'd be a teacher icon (e.g. below), so I think it should be clear enough.

<img width="275" alt="image" src="https://user-images.githubusercontent.com/19721219/217312260-b27ec68b-fe50-4f63-a8c9-e957012c75fe.png">

**Comment by CarsonHoffman** [comment]
I just implemented this in [b7480e4](https://github.com/CarsonHoffman/office-hours-queue/commit/b7480e4034c43db1c888761ce26513c4a4be5f74). Because it required server changes, I'll need to wait until tonight to deploy it. In the meantime, here's a preview of what it will look like (the last message appears when the staff member hits the "undo" button and is an unexpected case, which simply takes off the helped icon without popping into the stack; nothing pops up when the "done" button is hit, which is the old version of the "help" button):

<img width="655" alt="image" src="https://user-images.githubusercontent.com/19721219/217351425-c8d7f73e-1050-471a-beb2-939237a548e8.png">
<img width="640" alt="image" src="https://user-images.githubusercontent.com/19721219/217351433-443e952b-2e00-44c4-92c4-845bea83ed08.png">
<img width="486" alt="image" src="https://user-images.githubusercontent.com/19721219/217351439-5047b85a-b16b-4846-ae4a-80c6631748c6.png">
<img width="485" alt="image" src="https://user-images.githubusercontent.com/19721219/217351443-d485146d-87d3-414a-b43a-3aad012c5ad0.png">

**Comment by CarsonHoffman** [comment]
I've now deployed this, so I'm going to mark this as closed. Feel free to re-open if you have further suggestions on this feature; I don't necessarily consider it set-in-stone done.

**Comment by michigan-musicer** [comment]
Would it be possible to make students under "currently being helped" a different color? Our staff have been getting confused on who's being helped and who's waiting for help (which might just be a matter of getting used to the UI) and I imagine color-coding might help.

**Comment by michigan-musicer** [comment]
If possible, we also had a request to add a field on "currently being helped" students that specifies the staff member who is currently helping them.

**Comment by michigan-musicer** [comment]
Not to keep adding on feature requests but when moving someone from "awaiting help" to "currently being helped" it would be nice to reset the timer for how long the student has been waiting. Right now if someone's ticket says "30 minutes ago" I don't know if they've been waiting for 20 and helped for 10 (fine), or waiting for 10 and helped for 20 (gotta move on!).

**Comment by CarsonHoffman** [comment]
I'm not sure that's the right UI—at least personally, from a staff perspective, having that indicator available seems like it'd lead to a bit of breathing-down-necks when one meeting might take a bit longer than others. (This already happens sometimes even when there isn't a direct indicator of how long a meeting is taking, so I think this might exacerbate things.) I think this is probably best kept track of on your own.

**Comment by michigan-musicer** [comment]
I might've written that in a weird way -- I meant that even if I just want to keep track of my own time spent, it's hard because I now need to keep track of where the timer was when I started helping. I didn't mean it in the sense of micromanaging others. I think your point is valid, but I also think it's a social / people problem and not a UI problem necessarily.
Before this change, we were able to accurately gauge how much time we individually spent helping students by seeing how long they've been popped. I don't think we were breathing down each other's necks? But I also see what you mean because we couldn't tell whether a popped student was done or was still being helped. I'd be curious to see other instructors' opinions on this.

**Comment by Parker121201** [comment]
I think the queue position number that appears in the title of the website is more misleading now. I think it would be better represented without the people currently being helped included in a student's queue position.

A student might be next up to be helped but sees that they are # 8 in the queue and not ready for someone to join very soon.
For a queue, you think of the # 1 spot as next up, not something like # 4 or # 8 depending on the number of staff working the queue.
