### ISSUE TITLE
[Enhancement] Limit Queue Size

### ISSUE THREAD

**Issue by xia-steven** [CarsonHoffman/office-hours-queue#43]
Is it possible to automatically close the queue when a certain number of students join the queue?

**Comment by CarsonHoffman** [comment]
I don't think this is the right solution for a variety of reasons,  including:

- This would only be feasible on manual-open queues rather than scheduled ones, and adding the conditional logic for both the back-end and UI here would start to balloon.
- At a more fundamental level, I'm not sure that a program enforcing whether or not someone can get help is the right UI on the student side. It's one thing to have the staff close the queue for time reasons, but taking that decision element out of it may feel a bit cold to students. The impacts of this system on a wider level is already something I've been considering for a long time.
- I'm not sure this need is widespread; I've only seen a few courses close the queue early in response to demand.

I'm going to have to say no on this one, sorry.
