### ISSUE TITLE
[Enhancement] Don't add hover background for course titles

### ISSUE THREAD

**Issue by seshrs** [CarsonHoffman/office-hours-queue#5]
When I first visited the Queue page, I was surprised that I couldn't click the name of the course. Only then did I realize that I *must* click a Queue, not the course.

https://user-images.githubusercontent.com/12139762/104667643-86230780-56a4-11eb-8ec9-29452b3ea8ed.mov

To make it more obvious, it would be nice if the background of the course title didn't change on hover (to indicate that it's not clickable). Maybe also use a different `cursor` style, perhaps `not-allowed`?

**Comment by CarsonHoffman** [comment]
I'll file this into the category of "questionable UI decisions made because I was learning CSS and it looked cool" 😅. The down-arrow was intended to point the user towards the queues, but I do think that it could be confusing. I definitely think the hover appearing is an oversight; I'll go ahead and remove that.

**Comment by CarsonHoffman** [comment]
I've overhauled the menu a bit in 87ba6c0 (which is now deployed); I think it is overall more functional now. Let me know what you think of it!

**Comment by seshrs** [comment]
That looks much better! That also partially fixes #3 on most laptop displays, so I guess #3 can be deprioritized (or left up-for-grabs for future contributors 😉 )
